import type { ChatMessageRow } from '@/lib/types';

/** Образец для демонстрационного режима: одно обращение с ответом. */
export const DEMO_CHAT: ChatMessageRow[] = [
  {
    id: 2,
    user_id: 'demo-user',
    question: 'Какие сейчас есть закупки по гидроизоляции?',
    answer:
      'По гидроизоляции открыт один лот.\n\n**ТОО «КазЦинк»**, Восточно-Казахстанская область — гидроизоляция кровли, 45 000 000 тенге, приём заявок до 10 сентября.\n\nЛот попал в отбор по словам «гидроизоляция кровли»; направление — кровли и фасады.',
    status: 'answered',
    error: null,
    found_events: 0,
    found_tenders: 1,
    cost_usd: 0.001547,
    sources: {
      events: [],
      tenders: [
        {
          tender_id: 1,
          lot_no: '37074102',
          announce_no: 'Z1245370',
          title: 'Комплект гидроизоляции',
          customer_name: 'АО «Волковгеология»',
          customer_bin: '940740001484',
          organizer_name: null,
          trade_method_name: 'Тендеры и конкурсы',
          amount: 11960000,
          qty: 200,
          unit: 'Комплект',
          ktru_code: '239919.900.000007',
          kato_name: 'Туркестанская область',
          delivery_place: 'Туркестанская область',
          published_at: '2026-08-27T05:00:00+05:00',
          apply_to: '2026-09-07T05:00:00+05:00',
          hours_left: 150,
          urgency: 'normal',
          importance: 5,
          match_reason: 'назван бренд или товар: Гидроизоляция',
          matched_on: 'гидроизоляция',
          entity_names: 'Гидроизоляция',
          portal_status: 'active',
          source: 'tenderbot',
          link: 'https://zakup.sk.kz/',
        },
      ],
    },
    asked_at: '2026-08-31T12:20:00+05:00',
    answered_at: '2026-08-31T12:20:04+05:00',
  },
  {
    id: 1,
    user_id: 'demo-user',
    question: 'Что нового по Тиккуриле?',
    answer:
      'По Тиккуриле в системе ничего не собрано за последние 21 день. Ниже — главное по отрасли за период.\n\n- Wildberries строит складской комплекс на 260 тыс. кв. м\n- В Караганде начали строить мост через Нуру',
    status: 'answered',
    error: null,
    found_events: 5,
    found_tenders: 0,
    cost_usd: 0.002104,
    sources: {
      events: [
        {
          event_id: 1,
          event_date: '2026-08-28T10:00:00+05:00',
          category: 'новость отрасли',
          importance: 4,
          sentiment: 'нейтральная',
          title: 'Wildberries строит складской комплекс на 260 тыс. кв. м',
          vyzhimka:
            'Логистический комплекс под Алматы: промышленные полы, гидроизоляция фундаментов, огнезащита конструкций.',
          entity_names: 'Промышленные полы и напольные покрытия, Склады и логистические комплексы',
          product_groups: 'Промышленные полы, Гидроизоляция',
          source_name: 'Kapital.kz',
          source_kind: 'news',
          link: 'https://kapital.kz/',
        },
      ],
      tenders: [],
    },
    asked_at: '2026-08-31T11:02:00+05:00',
    answered_at: '2026-08-31T11:02:05+05:00',
  },
];
