/**
 * Демонстрационный набор. Изолирован полностью: он не пишется ни в одну
 * таблицу и включается только переменной DASHBOARD_DEMO=1. Сущности взяты
 * реальные — те же, что в словаре системы, — чтобы демонстрация не расходилась
 * с предметной областью.
 */

import type {
  AdminHealth,
  BrandStatsRow,
  CompetitorActivityRow,
  CompetitorChangeRow,
  CompetitorPageRow,
  DashboardKpi,
  DeliveryStateRow,
  EventListRow,
  FailedRunRow,
  LlmDailyRow,
  SourceStatsRow,
  StopWordRow,
  SubscriptionRow,
  TenderCardRow,
  ThresholdRow,
  WorkflowHealthRow,
} from '@/lib/types';

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const hoursAhead = (h: number) => new Date(now + h * 3600_000).toISOString();

export const DEMO_KPI: DashboardKpi = {
  events_period: 11,
  events_high_7d: 12,
  tenders_open: 19,
  competitor_changes: 126,
  collect_success_pct: 89,
  runs_total_24h: 228,
  runs_ok_24h: 202,
  materials_period: 77,
  last_event_at: hoursAgo(3),
  last_run_at: hoursAgo(0.2),
};

export const DEMO_EVENTS: EventListRow[] = [
  {
    event_id: 201,
    agent: 'competitor',
    category: 'действие конкурента',
    importance: 4,
    sentiment: 'отрицательная',
    title: 'Kova-Technology заменила товарные категории каталога',
    summary:
      'Компания удалила 10 категорий автомобильных запчастей и расходников и добавила 10 новых: офисное ПО, детскую литературу, рольставни, декоративные экраны, туалетное оборудование.',
    rationale: 'Смена профиля каталога у наблюдаемого конкурента меняет пересечение по ассортименту.',
    brief: 'Компания удалила 10 категорий автозапчастей и добавила 10 новых, включая рольставни и декоративные экраны.',
    product_focus: null,
    product_groups: null,
    company_focus: 'Kova-Technology',
    entity_names: 'Kova-Technology',
    source_name: 'сайт конкурента',
    source_kind: 'site',
    source_code: 'competitor_sites',
    link: 'https://kova-technology.kz/',
    event_date: hoursAgo(4),
    created_at: hoursAgo(3),
    is_notified: true,
    in_digest: false,
    entity_ids: [33],
    entity_types: ['competitor'],
    duplicates_count: 0,
    direction_verdict: 'pass',
    direction_what: 'Новый продукт или линейка',
    direction_geo: 'Казахстан',
    direction_weight: 1.6,
  },
  {
    event_id: 202,
    agent: 'news',
    category: 'новость отрасли',
    importance: 3,
    sentiment: 'нейтральная',
    title: 'Mapei открыла новый производственный объект в Бернли',
    summary: 'Mapei UK расширяет производственную базу группы в Великобритании.',
    rationale: 'Расширение производства конкурирующего бренда без прямого влияния на рынок Казахстана.',
    brief: 'Mapei UK открыла новый производственный объект в Бернли.',
    product_focus: 'Mapei',
    product_groups: 'строительная химия',
    company_focus: null,
    entity_names: 'Mapei',
    source_name: 'Поиск и новости (Brave Search)',
    source_kind: 'search',
    source_code: 'brave_web',
    link: 'https://example.com/mapei-burnley',
    event_date: hoursAgo(20),
    created_at: hoursAgo(18),
    is_notified: false,
    in_digest: true,
    entity_ids: [41],
    entity_types: ['brand'],
    duplicates_count: 0,
    direction_verdict: 'pass',
    direction_what: 'Новый продукт или линейка',
    direction_geo: 'Казахстан',
    direction_weight: 1.6,
  },
  {
    event_id: 199,
    agent: 'news',
    category: 'технология',
    importance: 3,
    sentiment: 'нейтральная',
    title: 'Обзор критериев выбора промышленных полов',
    summary: 'Разбор подбора покрытий под тип объекта и нагрузку.',
    rationale: 'Отраслевая тема без привязки к конкретному игроку.',
    brief: 'Разбор подбора покрытий под тип объекта и нагрузку.',
    product_focus: 'Промышленные полы',
    product_groups: null,
    company_focus: null,
    entity_names: 'Промышленные полы',
    source_name: 'Публичные каналы Telegram',
    source_kind: 'social',
    source_code: 'telegram_channels',
    link: 'https://t.me/s/example/1',
    event_date: hoursAgo(30),
    created_at: hoursAgo(27),
    is_notified: false,
    in_digest: true,
    entity_ids: [58],
    entity_types: ['product'],
    duplicates_count: 0,
    direction_verdict: 'pass',
    direction_what: 'Новый продукт или линейка',
    direction_geo: 'Казахстан',
    direction_weight: 1.6,
  },
  {
    event_id: 198,
    agent: 'news',
    category: 'действие конкурента',
    importance: 2,
    sentiment: 'нейтральная',
    title: 'Jotun представил Jotashield Infinity для наружных работ',
    summary: 'Новая позиция в фасадных ЛКМ у конкурента по краскам.',
    rationale: 'Новый товар в смежной категории.',
    brief: 'Новая позиция в фасадных ЛКМ у конкурента по краскам.',
    product_focus: 'Jotun',
    product_groups: 'ЛКМ',
    company_focus: null,
    entity_names: 'Jotun',
    source_name: 'Поиск и новости (Brave Search)',
    source_kind: 'search',
    source_code: 'brave_web',
    link: 'https://example.com/jotun',
    event_date: hoursAgo(50),
    created_at: hoursAgo(47),
    is_notified: false,
    in_digest: true,
    entity_ids: [37],
    entity_types: ['brand'],
    duplicates_count: 0,
    direction_verdict: 'pass',
    direction_what: 'Новый продукт или линейка',
    direction_geo: 'Казахстан',
    direction_weight: 1.6,
  },
  {
    event_id: 166,
    agent: 'news',
    category: 'новость отрасли',
    importance: 3,
    sentiment: 'положительная',
    title: 'Sika расширяет линейку гидроизоляции',
    summary: 'Производитель объявил о выводе новых составов для подземной гидроизоляции.',
    rationale: 'Расширение линейки поставляемого нами бренда.',
    brief: 'Производитель объявил о выводе новых составов для подземной гидроизоляции.',
    product_focus: 'Sika · Гидроизоляция',
    product_groups: 'гидроизоляция, строительная химия',
    company_focus: null,
    entity_names: 'Sika, Гидроизоляция',
    source_name: 'Публичные каналы Telegram',
    source_kind: 'social',
    source_code: 'telegram_channels',
    link: 'https://t.me/s/example/2',
    event_date: hoursAgo(70),
    created_at: hoursAgo(66),
    is_notified: false,
    in_digest: true,
    entity_ids: [22, 61],
    entity_types: ['brand', 'topic'],
    duplicates_count: 0,
    direction_verdict: 'pass',
    direction_what: 'Новый продукт или линейка',
    direction_geo: 'Казахстан',
    direction_weight: 1.6,
  },
];

export const DEMO_COMPETITORS: CompetitorActivityRow[] = [
  {
    competitor_id: 1,
    name: 'Kova-Technology',
    base_url: 'https://kova-technology.kz',
    entity_id: 33,
    is_active: true,
    events_count: 37,
    changes_count: 62,
    significant_count: 21,
    change_types: 'section_changed',
    last_change_at: hoursAgo(4),
    last_crawled_at: hoursAgo(1),
    pages_active: 1,
    pages_ok: 1,
    pages_failing_hard: 0,
    crawl_success_pct: 100,
    crawl_health: 'ok',
  },
  {
    competitor_id: 2,
    name: 'Leman Pro',
    base_url: 'https://lemanapro.kz',
    entity_id: 45,
    is_active: true,
    events_count: 12,
    changes_count: 65,
    significant_count: 18,
    change_types: 'category_changed, product_added, product_removed, section_changed',
    last_change_at: hoursAgo(26),
    last_crawled_at: hoursAgo(2),
    pages_active: 8,
    pages_ok: 8,
    pages_failing_hard: 0,
    crawl_success_pct: 100,
    crawl_health: 'ok',
  },
  {
    competitor_id: 3,
    name: 'Кристаллизол',
    base_url: 'https://kristallizol.kz',
    entity_id: 52,
    is_active: true,
    events_count: 11,
    changes_count: 14,
    significant_count: 6,
    change_types: 'category_changed, section_changed',
    last_change_at: hoursAgo(30),
    last_crawled_at: hoursAgo(3),
    pages_active: 2,
    pages_ok: 1,
    pages_failing_hard: 0,
    crawl_success_pct: 50,
    crawl_health: 'warning',
  },
  {
    competitor_id: 4,
    name: 'Knauf',
    base_url: 'https://knauf.kz',
    entity_id: 55,
    is_active: true,
    events_count: 10,
    changes_count: 9,
    significant_count: 3,
    change_types: 'section_changed',
    last_change_at: hoursAgo(52),
    last_crawled_at: hoursAgo(40),
    pages_active: 2,
    pages_ok: 0,
    pages_failing_hard: 2,
    crawl_success_pct: 0,
    crawl_health: 'critical',
  },
];

export const DEMO_PAGES: CompetitorPageRow[] = [
  {
    id: 11,
    competitor_id: 1,
    url: 'https://kova-technology.kz/',
    section_type: 'catalog',
    is_active: true,
    last_crawled_at: hoursAgo(1),
    last_change_at: hoursAgo(4),
    crawl_status: 'ok',
    fetch_mode: 'http',
    fail_count: 0,
    min_interval_hours: 20,
  },
];

export const DEMO_CHANGES: CompetitorChangeRow[] = [
  {
    id: 501,
    page_id: 11,
    change_type: 'section_changed',
    diff_summary:
      'Удалено 10 категорий автозапчастей, добавлено 10 новых: офисное ПО, детская литература, рольставни.',
    diff_chars: 812,
    is_significant: true,
    reject_reason: null,
    status: 'analyzed',
    detected_at: hoursAgo(4),
  },
];

export const DEMO_BRANDS: BrandStatsRow[] = [
  {
    entity_id: 22,
    canonical_name: 'Sika',
    entity_type: 'brand',
    product_group: 'строительная химия',
    relation: null,
    geo_scope: 'весь мир',
    search_priority: 1,
    is_active: true,
    aliases_count: 6,
    events_count: 18,
    events_high: 2,
    share_pct: 9.6,
    last_event_at: hoursAgo(66),
    positive: 7,
    neutral: 10,
    negative: 1,
    recipients: 'Альберт Гаан',
    subscribers: 1,
    coverage_gap: false,
  },
  {
    entity_id: 61,
    canonical_name: 'Гидроизоляция',
    entity_type: 'topic',
    product_group: 'гидроизоляция',
    relation: null,
    geo_scope: 'только Казахстан',
    search_priority: 1,
    is_active: true,
    aliases_count: 4,
    events_count: 22,
    events_high: 1,
    share_pct: 11.8,
    last_event_at: hoursAgo(66),
    positive: 6,
    neutral: 15,
    negative: 1,
    recipients: '',
    subscribers: 0,
    coverage_gap: true,
  },
  {
    entity_id: 41,
    canonical_name: 'Mapei',
    entity_type: 'brand',
    product_group: 'строительная химия',
    relation: 'DIRECT_COMPETITOR',
    geo_scope: 'только Казахстан',
    search_priority: 2,
    is_active: true,
    aliases_count: 3,
    events_count: 11,
    events_high: 0,
    share_pct: 5.9,
    last_event_at: hoursAgo(18),
    positive: 1,
    neutral: 9,
    negative: 1,
    recipients: '',
    subscribers: 0,
    coverage_gap: true,
  },
  {
    entity_id: 19,
    canonical_name: 'Tikkurila',
    entity_type: 'brand',
    product_group: 'ЛКМ',
    relation: null,
    geo_scope: 'только Казахстан',
    search_priority: 1,
    is_active: true,
    aliases_count: 5,
    events_count: 3,
    events_high: 0,
    share_pct: 1.6,
    last_event_at: hoursAgo(140),
    positive: 1,
    neutral: 2,
    negative: 0,
    recipients: 'Менеджер по ЛКМ',
    subscribers: 1,
    coverage_gap: false,
  },
  {
    entity_id: 27,
    canonical_name: 'Selena',
    entity_type: 'brand',
    product_group: 'монтажная химия',
    relation: null,
    geo_scope: 'только Казахстан',
    search_priority: 2,
    is_active: true,
    aliases_count: 3,
    events_count: 0,
    events_high: 0,
    share_pct: 0,
    last_event_at: null,
    positive: 0,
    neutral: 0,
    negative: 0,
    recipients: 'Менеджер по Selena',
    subscribers: 1,
    coverage_gap: false,
  },
];

export const DEMO_TENDERS: TenderCardRow[] = [
  {
    tender_id: 9001,
    source: 'goszakup',
    lot_no: '12345678-ЗЦП1',
    announce_no: '12345678-1',
    title: 'Гидроизоляционные материалы проникающего действия для подвала',
    announce_title: 'Приобретение материалов для капитального ремонта',
    description: 'Материал проникающего действия, расход по проекту.',
    customer_name: 'ГКП «Тепловодоснабжение»',
    customer_bin: '123456789012',
    organizer_name: null,
    trade_method: 'Запрос ценовых предложений',
    trade_method_name: null,
    kato_name: null,
    also_sources: null,
    portal_status: 'Опубликовано',
    amount: 4_820_000,
    qty: 1200,
    unit: 'кг',
    ktru_code: '239410.500.000001',
    kato: 'Кызылординская область',
    delivery_place: null,
    delivery_term: '30 календарных дней',
    published_at: hoursAgo(9),
    apply_from: hoursAgo(9),
    apply_to: hoursAhead(19),
    importance: 5,
    is_relevant: true,
    match_reason: 'гидроизоляция, проникающая гидроизоляция',
    enriched: true,
    is_notified: true,
    reminder_sent: false,
    created_at: hoursAgo(9),
    updated_at: hoursAgo(1),
    link: 'https://goszakup.gov.kz/ru/subpriceoffer/index/1/1',
    hours_left: 19,
    urgency: 'critical',
    matched_on: 'гидроизоляция, проникающая гидроизоляция',
    match_types: 'keyword, brand',
    has_brand: true,
    entity_names: 'Гидроизоляция',
    entity_ids: [61],
  },
  {
    tender_id: 9002,
    source: 'goszakup',
    lot_no: '12345679-ОТ1',
    announce_no: '12345679-1',
    title: 'Наливные полы промышленные',
    announce_title: 'Ремонт спортивного зала',
    description: null,
    customer_name: 'КГУ «Школа-гимназия №14»',
    customer_bin: '123456789013',
    organizer_name: null,
    trade_method: 'Открытый конкурс',
    trade_method_name: null,
    kato_name: null,
    also_sources: null,
    portal_status: 'Опубликовано',
    amount: 11_300_000,
    qty: 600,
    unit: 'м2',
    ktru_code: null,
    kato: 'Кызылорда',
    delivery_place: null,
    delivery_term: null,
    published_at: hoursAgo(20),
    apply_from: hoursAgo(20),
    apply_to: hoursAhead(48),
    importance: 4,
    is_relevant: true,
    match_reason: 'наливной пол',
    enriched: true,
    is_notified: true,
    reminder_sent: false,
    created_at: hoursAgo(20),
    updated_at: hoursAgo(2),
    link: 'https://goszakup.gov.kz/ru/subpriceoffer/index/2/2',
    hours_left: 48,
    urgency: 'warning',
    matched_on: 'наливной пол',
    match_types: 'keyword',
    has_brand: false,
    entity_names: 'Промышленные полы',
    entity_ids: [58],
  },
  {
    tender_id: 9003,
    source: 'goszakup',
    lot_no: '12345680-ЗЦП1',
    announce_no: '12345680-1',
    title: 'Ремонтные составы для бетона',
    announce_title: 'Текущий ремонт сетей',
    description: null,
    customer_name: 'ТОО «Городские сети»',
    customer_bin: '123456789014',
    organizer_name: null,
    trade_method: 'Запрос ценовых предложений',
    trade_method_name: null,
    kato_name: null,
    also_sources: null,
    portal_status: 'Опубликовано',
    amount: 760_000,
    qty: 300,
    unit: 'кг',
    ktru_code: null,
    kato: 'Кызылорда',
    delivery_place: null,
    delivery_term: null,
    published_at: hoursAgo(40),
    apply_from: hoursAgo(40),
    apply_to: hoursAhead(144),
    importance: 3,
    is_relevant: true,
    match_reason: 'ремонтный состав',
    enriched: true,
    is_notified: false,
    reminder_sent: false,
    created_at: hoursAgo(40),
    updated_at: hoursAgo(5),
    link: 'https://goszakup.gov.kz/ru/subpriceoffer/index/3/3',
    hours_left: 144,
    urgency: 'normal',
    matched_on: 'ремонтный состав',
    match_types: 'keyword',
    has_brand: false,
    entity_names: null,
    entity_ids: [],
  },
];

export const DEMO_STOP_WORDS: StopWordRow[] = [
  {
    stop_word: 'штемпельная',
    filtered_count: 4,
    examples: 'Приобретение краски штемпельной Trodat · Канцелярские товары',
  },
  { stop_word: 'канцелярск', filtered_count: 2, examples: 'Приобретение канцелярских товаров' },
];

export const DEMO_SOURCES: SourceStatsRow[] = [
  {
    source_id: 3,
    code: 'telegram_channels',
    name: 'Публичные каналы Telegram',
    kind: 'social',
    is_active: true,
    connected: true,
    missing: '',
    blocker: '',
    workflow_code: 'WF-14',
    expected_interval_min: 180,
    materials_total: 600,
    materials_period: 41,
    share_pct: 63.4,
    events_total: 29,
    events_period: 5,
    accounts_active: 10,
    last_activity_at: hoursAgo(5),
    last_material_at: hoursAgo(5),
    last_success_at: hoursAgo(2),
    runs_ok_24h: 8,
    runs_failed_24h: 0,
    avg_duration_ms: 4200,
    last_error: null,
    last_error_at: null,
    freshness: 'active',
  },
  {
    source_id: 1,
    code: 'brave_web',
    name: 'Поиск и новости (Brave Search)',
    kind: 'search',
    is_active: true,
    connected: true,
    missing: '',
    blocker: '',
    workflow_code: 'WF-01',
    expected_interval_min: 180,
    materials_total: 346,
    materials_period: 36,
    share_pct: 36.6,
    events_total: 111,
    events_period: 6,
    accounts_active: 0,
    last_activity_at: hoursAgo(6),
    last_material_at: hoursAgo(6),
    last_success_at: hoursAgo(3),
    runs_ok_24h: 6,
    runs_failed_24h: 0,
    avg_duration_ms: 9100,
    last_error: null,
    last_error_at: null,
    freshness: 'active',
  },
  {
    source_id: 4,
    code: 'goszakup',
    name: 'Госзакупки Республики Казахстан',
    kind: 'registry',
    is_active: true,
    connected: true,
    missing: '',
    blocker: '',
    workflow_code: 'WF-11',
    expected_interval_min: 15,
    materials_total: 0,
    materials_period: 0,
    share_pct: 0,
    events_total: 0,
    events_period: 0,
    accounts_active: 0,
    last_activity_at: hoursAgo(0.2),
    last_material_at: null,
    last_success_at: hoursAgo(0.2),
    runs_ok_24h: 69,
    runs_failed_24h: 6,
    avg_duration_ms: 5100,
    last_error: '{"diagnostics":[{"term":"краска","ok":false,"reason":"ответ 502"}]}',
    last_error_at: hoursAgo(1.5),
    freshness: 'active',
  },
  {
    source_id: 2,
    code: 'competitor_sites',
    name: 'Сайты конкурентов (Firecrawl)',
    kind: 'crawl',
    is_active: true,
    connected: true,
    missing: '',
    blocker: '',
    workflow_code: 'WF-03',
    expected_interval_min: 1440,
    materials_total: 0,
    materials_period: 0,
    share_pct: 0,
    events_total: 0,
    events_period: 0,
    accounts_active: 0,
    last_activity_at: hoursAgo(1),
    last_material_at: null,
    last_success_at: hoursAgo(1),
    runs_ok_24h: 10,
    runs_failed_24h: 0,
    avg_duration_ms: 15400,
    last_error: null,
    last_error_at: null,
    freshness: 'active',
  },
  {
    source_id: 5,
    code: 'vk',
    name: 'VK',
    kind: 'social',
    is_active: true,
    connected: true,
    missing: '',
    blocker: 'нет наблюдаемых сообществ',
    workflow_code: 'WF-14',
    expected_interval_min: 180,
    materials_total: 0,
    materials_period: 0,
    share_pct: 0,
    events_total: 0,
    events_period: 0,
    accounts_active: 0,
    last_activity_at: null,
    last_material_at: null,
    last_success_at: hoursAgo(2),
    runs_ok_24h: 8,
    runs_failed_24h: 0,
    avg_duration_ms: 4200,
    last_error: null,
    last_error_at: null,
    freshness: 'idle',
  },
  {
    source_id: 6,
    code: 'google_cse',
    name: 'Поиск Google (Programmable Search)',
    kind: 'search',
    is_active: false,
    connected: false,
    missing: 'google_api_key, google_cse_id',
    blocker: 'не заполнено: google_api_key, google_cse_id',
    workflow_code: 'WF-17',
    expected_interval_min: 180,
    materials_total: 0,
    materials_period: 0,
    share_pct: 0,
    events_total: 0,
    events_period: 0,
    accounts_active: 0,
    last_activity_at: null,
    last_material_at: null,
    last_success_at: null,
    runs_ok_24h: 0,
    runs_failed_24h: 0,
    avg_duration_ms: null,
    last_error: null,
    last_error_at: null,
    freshness: 'not_connected',
  },
  {
    source_id: 7,
    code: 'perplexity',
    name: 'Perplexity (исследовательские запросы)',
    kind: 'search',
    is_active: false,
    connected: true,
    missing: '',
    blocker: 'источник выключен',
    workflow_code: 'WF-19',
    expected_interval_min: 1440,
    materials_total: 0,
    materials_period: 0,
    share_pct: 0,
    events_total: 0,
    events_period: 0,
    accounts_active: 0,
    last_activity_at: null,
    last_material_at: null,
    last_success_at: null,
    runs_ok_24h: 0,
    runs_failed_24h: 0,
    avg_duration_ms: null,
    last_error: null,
    last_error_at: null,
    freshness: 'disabled',
  },
  {
    source_id: 8,
    code: 'tender_api',
    name: 'Тендерный API (внешний поставщик данных о закупках)',
    kind: 'api',
    is_active: false,
    connected: false,
    missing: 'tender_api_base_url',
    blocker: 'не заполнено: tender_api_base_url',
    workflow_code: 'WF-20',
    expected_interval_min: 30,
    materials_total: 0,
    materials_period: 0,
    share_pct: 0,
    events_total: 0,
    events_period: 0,
    accounts_active: 0,
    last_activity_at: null,
    last_material_at: null,
    last_success_at: null,
    runs_ok_24h: 0,
    runs_failed_24h: 0,
    avg_duration_ms: null,
    last_error: null,
    last_error_at: null,
    freshness: 'not_connected',
  },
];

export const DEMO_ADMIN_HEALTH: AdminHealth = {
  runs_total_24h: 228,
  runs_ok_24h: 202,
  runs_failed_24h: 6,
  runs_partial_24h: 20,
  runs_running: 0,
  success_rate_pct: 88.6,
  avg_duration_ms: 5549,
  collected_24h: 20,
  classified_24h: 19,
  dedup_share_pct: 39.4,
  filter_share_pct: 75.3,
  events_high_24h: 1,
  queue_new: 0,
  spent_today_usd: 0.052,
  spent_month_usd: 0.91,
  spent_total_usd: 0.91,
  budget_month_usd: 2,
  budget_used_pct: 45.5,
  llm_calls_month: 182,
  tokens_in_month: 812_400,
  tokens_out_month: 96_300,
  notifications_30d: 13,
  digests_total: 14,
  last_digest_at: hoursAgo(9),
  last_backup_at: hoursAgo(120),
  pages_active: 18,
  pages_failing: 0,
  dict_entities: 125,
  events_total: 187,
  last_run_at: hoursAgo(0.2),
};

export const DEMO_WORKFLOWS: WorkflowHealthRow[] = [
  {
    workflow_code: 'WF-11',
    workflow_name: 'Tender Watch',
    runs_total: 96,
    runs_ok: 69,
    runs_failed: 6,
    runs_partial: 21,
    runs_running: 0,
    success_rate: 71.9,
    avg_duration_ms: 5100,
    items_out: 512,
    last_run_at: hoursAgo(0.2),
    last_status: 'success',
    next_expected_at: hoursAhead(0.05),
  },
  {
    workflow_code: 'WF-01',
    workflow_name: 'News Ingest',
    runs_total: 8,
    runs_ok: 6,
    runs_failed: 0,
    runs_partial: 2,
    runs_running: 0,
    success_rate: 75,
    avg_duration_ms: 9100,
    items_out: 20,
    last_run_at: hoursAgo(3),
    last_status: 'success',
    next_expected_at: hoursAhead(0.4),
  },
  {
    workflow_code: 'WF-02',
    workflow_name: 'Enrich & Classify',
    runs_total: 8,
    runs_ok: 8,
    runs_failed: 0,
    runs_partial: 0,
    runs_running: 0,
    success_rate: 100,
    avg_duration_ms: 12400,
    items_out: 19,
    last_run_at: hoursAgo(2.7),
    last_status: 'success',
    next_expected_at: hoursAhead(0.6),
  },
];

export const DEMO_FAILED_RUNS: FailedRunRow[] = [
  {
    id: 8801,
    workflow_code: 'WF-11',
    workflow_name: 'Tender Watch',
    execution_id: '2251',
    started_at: hoursAgo(5),
    finished_at: hoursAgo(4.99),
    duration_ms: 3400,
    status: 'partial',
    items_in: 6,
    items_out: 41,
    error_text: 'фильтр не применился, выдача 10000',
  },
  {
    id: 8790,
    workflow_code: 'WF-11',
    workflow_name: 'Tender Watch',
    execution_id: '2240',
    started_at: hoursAgo(9),
    finished_at: hoursAgo(8.99),
    duration_ms: 25000,
    status: 'failed',
    items_in: 6,
    items_out: 0,
    error_text: 'ответ 502 от goszakup.gov.kz',
  },
];

export const DEMO_LLM_DAILY: LlmDailyRow[] = Array.from({ length: 14 }).map((_, i) => {
  const d = new Date(now - (13 - i) * 86_400_000);
  const base = [0.02, 0.05, 0.09, 0.07, 0.04, 0.06, 0.08, 0.05, 0.03, 0.07, 0.06, 0.05, 0.09, 0.052];
  return {
    day: d.toISOString().slice(0, 10),
    calls: 8 + ((i * 3) % 11),
    cost_usd: base[i] ?? 0.05,
    tokens_in: 40_000 + i * 2500,
    tokens_out: 4_000 + i * 300,
  };
});

export const DEMO_DELIVERY: DeliveryStateRow[] = [
  { kind: 'instant', sent_total: 13, sent_30d: 13, failed_30d: 0, last_sent_at: hoursAgo(3) },
  { kind: 'daily', sent_total: 16, sent_30d: 16, failed_30d: 0, last_sent_at: hoursAgo(9) },
  { kind: 'weekly', sent_total: 2, sent_30d: 2, failed_30d: 0, last_sent_at: hoursAgo(80) },
];

export const DEMO_SUBSCRIPTIONS: SubscriptionRow[] = [
  {
    id: 1,
    recipient_id: 4,
    recipient_name: 'Менеджер по ЛКМ',
    recipient_role: 'sales',
    recipient_active: true,
    scope: 'entity',
    target: 'Tikkurila',
    entity_id: 19,
    target_type: 'brand',
    mode: 'include',
    effective_min_importance: 2,
    channels: ['instant', 'daily'],
    note: 'форма',
    is_active: true,
    created_at: hoursAgo(50),
  },
  {
    id: 2,
    recipient_id: 5,
    recipient_name: 'Менеджер по Selena',
    recipient_role: 'sales',
    recipient_active: true,
    scope: 'entity',
    target: 'Selena',
    entity_id: 27,
    target_type: 'brand',
    mode: 'include',
    effective_min_importance: 3,
    channels: ['instant', 'daily'],
    note: 'форма',
    is_active: true,
    created_at: hoursAgo(50),
  },
];

export const DEMO_THRESHOLDS: ThresholdRow[] = [
  { key: 'tender_min_amount', value: '200000', value_num: 200000, description: 'Порог значимости лота, тенге' },
  { key: 'instant_importance_min', value: '4', value_num: 4, description: 'Порог немедленных уведомлений' },
  { key: 'route_bypass_importance', value: '5', value_num: 5, description: 'Важность, приходящая всем' },
  { key: 'llm_budget_usd_month', value: '2', value_num: 2, description: 'Предел расхода на модель за месяц' },
  { key: 'norm_page_fail_max', value: '3', value_num: 3, description: 'Падений подряд до тревоги по странице' },
];
